FROM daniellarusso/steamcmd:ubuntu-bionic

ARG STEAM_ACCOUNT_USER=${STEAM_ACCOUNT_USER}
ARG STEAM_ACCOUNT_PASSWORD=${STEAM_ACCOUNT_PASSWORD}

ARG ARMA3SERVER_NAME=arma3server
ARG ARMA3SERVER_DIR=${STEAM_USER_DIR}/${ARMA3SERVER_NAME}
ARG ARMA3SERVER_APP_ID=233780
ARG ARMA3SERVER_BINARY=arma3server_x64

USER ${STEAM_USER_NAME}

RUN mkdir -p ${ARMA3SERVER_DIR} \
 && steamcmd \
    +login ${STEAM_ACCOUNT_USER} ${STEAM_ACCOUNT_PASSWORD} \
    +force_install_dir ${ARMA3SERVER_DIR} \
    +app_update ${ARMA3SERVER_APP_ID} validate \
    +quit

COPY --chown=${STEAM_USER_NAME}:${STEAM_USER_GROUP} entrypoint.sh ${ARMA3SERVER_DIR}/entrypoint.sh

RUN chmod +x ${ARMA3SERVER_DIR}/entrypoint.sh

WORKDIR ${ARMA3SERVER_DIR}

EXPOSE 2302-2306/udp

ENTRYPOINT ["./entrypoint.sh"]