version: "3.7"

services:
  arma:
    build:
      context: .
      args:
        - ARMA3SERVER_PARAMETER_MOD=${ARMA3SERVER_PARAMETER_MOD}
        - ARMA3SERVER_PARAMETER_SERVERMOD=${ARMA3SERVER_PARAMETER_SERVERMOD}
        - STEAM_ACCOUNT_USER=${STEAM_ACCOUNT_USER}
        - STEAM_ACCOUNT_PASSWORD=${STEAM_ACCOUNT_PASSWORD}
    ports:
      - "2302-2306:2302-2306/udp"
    volumes:
      - ./configs:/home/steam/arma3server/configs
      - ./keys:/home/steam/arma3server/keys
      - ./mods:/home/steam/arma3server/mods
      - ./mpmissions:/home/steam/arma3server/mpmissions
      - ./profiles:/home/steam/arma3server/profiles
      - ./servermods:/home/steam/arma3server/servermods

  ftp:
    image: daniellarusso/vsftpd
    ports:
      - "21:21"
    volumes:
      - ./mods:/var/lib/ftp