version: "3.7"

services:
  arma:
    image: synixebrett/arma3server
    ports:
      - 2302:2302
      - 2303:2303
      - 2304:2304
      - 2305:2305
    volumes:
      - ./data/arma/mpmissions:/arma3/mpmissions
      - ./data/arma/configs:/arma3/configs
      - ./data/arma/mods:/arma3/mods
      - ./data/arma/servermods:/arma3/servermods
    environment:
      ARMA_CONFIG: ${ARMA_CONFIG}
      STEAM_USER: ${STEAM_USER}
      STEAM_PASSWORD: ${STEAM_PASSWORD}
