version: "3.7"

services:
  arma:
    build:
      context: .
      args:
        - ARMA3SERVER_PARAMETER_MOD=${ARMA3SERVER_PARAMETER_MOD}
        - ARMA3SERVER_PARAMETER_SERVERMOD=${ARMA3SERVER_PARAMETER_SERVERMOD}
        - STEAM_ACCOUNT_USER=${STEAM_ACCOUNT_USER}
        - STEAM_ACCOUNT_PASSWORD=${STEAM_ACCOUNT_PASSWORD}
    ports:
      - "2302:2302/udp"
      - "2303:2303/udp"
      - "2304:2304/udp"
      - "2305:2305/udp"
      - "2306:2306/udp"
    volumes:
      - ./configs:/home/steam/arma3server/configs
      - ./keys:/home/steam/arma3server/keys
      - ./mods:/home/steam/arma3server/mods
      - ./mpmissions:/home/steam/arma3server/mpmissions
      - ./profiles:/home/steam/arma3server/profiles
      - ./servermods:/home/steam/arma3server/servermods