version: "3.7"

services:
  arma:
    build:
      context: .
    environment:
      - ARMA3SERVER_PARAMETER_MOD=${ARMA3SERVER_PARAMETER_MOD}
      - ARMA3SERVER_PARAMETER_SERVERMOD=${ARMA3SERVER_PARAMETER_SERVERMOD}
      - ARMA3SERVER_UPDATE_ON_STARTUP=${ARMA3SERVER_UPDATE_ON_STARTUP:-false}
      - ARMA3SERVER_HEADLESS_CLIENTS=${ARMA3SERVER_HEADLESS_CLIENTS:-0}
      - STEAM_ACCOUNT_USER=${STEAM_ACCOUNT_USER}
      - STEAM_ACCOUNT_PASSWORD=${STEAM_ACCOUNT_PASSWORD}
    ports:
      - "2302-2306:2302-2306/udp"
    volumes:
      - ./configs:/home/steam/arma3server/configs
      - ./keys:/home/steam/arma3server/keys
      - ./mods:/home/steam/arma3server/mods
      - ./mpmissions:/home/steam/arma3server/mpmissions
      - ./profiles:/home/steam/arma3server/profiles
      - ./servermods:/home/steam/arma3server/servermods

  ftp:
    image: daniellarusso/vsftpd
    environment:
      - FTP_USER_UID=${FTP_USER_UID:-1000}
      - FTP_USER_NAME=${FTP_USER_NAME:-vsftpd}
      - FTP_USER_PASSWORD=${FTP_USER_PASSWORD}
      - FTP_PORT=${FTP_PORT:-21}
      - FTP_PASV_PORT_MIN=${FTP_PASV_PORT_MIN:-21000}
      - FTP_PASV_PORT_MAX=${FTP_PASV_PORT_MAX:-21010}
    ports:
      - "21:21"
    volumes:
      - ./mods:/var/lib/ftp
      - ./log:/var/log/