version: "3.7"

services:
  arma:
    image: synixebrett/arma3server
    ports:
      - 2302:2302
      - 2303:2303
      - 2304:2304
      - 2305:2305
      - 2306:2306
    volumes:
      - ./data/arma/mpmissions:/home/steam/arma3/mpmissions
      - ./data/arma/configs:/home/steam/arma3/configs
      - ./data/arma/mods:/home/steam/arma3/mods
      - ./data/arma/servermods:/home/steam/arma3/servermods
    environment:
      ARMA_BINARY: ${ARMA_BINARY}
      ARMA_CONFIG: ${ARMA_CONFIG}
      STEAM_PASSWORD: ${STEAM_PASSWORD}
      STEAM_USER: ${STEAM_USER}
